config/routes.rb
IPadQuiz::Application.routes.draw do


  root 'quizzes#home'

  get '/checkscore' => 'quizzes#checkscore'

  get '/results/:id' => 'results#showresults', :as => 'showresults'

  get '/results/:id' => 'results#show'


  resources :questions

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'


end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
end

app/models/result.rb
class Result < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :find_questions, except: [:index]

  def find_questions
    @question = Question.find_by(:id => params[:id])
  end

  def index

  end

  def show


    @all_questions = Question.where(quiz_id: 1)

    @last_question = Question.last

    @result = Result.find_by(:id => params[:currentresult])
    @result.total_score += params[:answervalue].to_i if params[:answervalue]
    @result.save

    @answers = Answer.where(question_id: @question.id)



  end


end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController


def home

@r = Result.new
@r.total_score = 0
@r.quiz_id = 1
@r.save



end



def checkscore

result = Result.find_by(:id => params[:currentresult])
result.total_score += params[:answervalue].to_i if params[:answervalue]
result.save

redirect_to showresults_url(result.id)

end




end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

def showresults

result = Result.find_by(:id => params[:id])

  if result.total_score > 30

    render "affirmative"

  else

    render "negative"

  end

end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IPadQuiz</title>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Alegreya+Sans+SC:100,400|Open+Sans:400,300|Merriweather+Sans:400,300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/index.html.erb
<h1>Questions#index</h1>
<p>Find me in app/views/questions/index.html.erb</p>

app/views/questions/show.html.erb
<section class="question-text">

  <h2><%= @question.question_text %></h2>

</section>

<section class="question-answers">

  <ul>

    <% @answers.each do |answer| %>

      <% if @question.id == @last_question.id %>

        <a href="/checkscore?answervalue=<%= answer.value %>&currentresult=<%= @result.id %>"><li><%= answer.answer_text %></li></a>

      <% else %>

        <a href="/questions/<%= @question.id + 1 %>?answervalue=<%= answer.value %>&currentresult=<%= @result.id %>&lastQid=<%= @question.id %>"><li><%= answer.answer_text %></li></a>

      <% end %>





    <% end %>

  </ul>

</section>
<% if params[:lastQid] %>
  <section class="feedback">

  <p><%= Question.find_by(id: params[:lastQid]).fact %></p>


  </section>
<% end %>

app/views/quizzes/home.html.erb
<div class="box">

  <section class="intro">
    <h1>Should You Buy an iPad?</h1>
    <p>Take this short quiz to find out if the iPad is a device you actually need.</p>
  </section>

  <section class="next">
    <%= link_to '<i class="fa fa-arrow-circle-o-right"></i>'.html_safe, question_url(id: '1', :currentresult => "#{@r.id}") %>
  </section>


  <footer>by @cbgriffin & @fire_pete</footer>
</div>

app/views/results/affirmative.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8 />
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>
<body>
  <div class="box">
    <section class="result">
      <h1>You Should Buy an iPad!</h1>
    </section>
    <section class="next">
      <i class="fa fa-thumbs-o-up"></i>
      <p>Based on your answers, it seems an iPad would be useful for you.</p><br>
      <!-- <a href="#"><i class="fa fa-twitter"></i>Share your result!</a> -->
    </section>
  </div>
</body>
</html>

app/views/results/negative.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8 />
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>
<body>
  <div class="box">
    <section class="result">
      <h1>You Should NOT Buy an iPad!</h1>
    </section>
    <section class="next">
      <i class="fa fa-frown-o"></i>
      <p>Based on your answers, it seems an iPad would be a pointless purchase for you.</p><br>
      <!-- <a href="#"><i class="fa fa-twitter"></i>Share your result!</a> -->
    </section>
  </div>
</body>
</html>